---
- name: stop apache
  systemd: name=apache2 state=stopped
- name: install nginx
  apt: name=nginx update_cache=yes state=present

- name: install passenger and other packages
  apt: name=dirmngr  state=present
- name: install passenger and other packages
  apt: name=gnupg state=present

- name: install PGP key
  shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7"
- name: install Certificate
  shell: "apt install -y apt-transport-https ca-certificates"
- name: add repo
  shell: "sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main > /etc/apt/sources.list.d/passenger.list'"
- name: apt update
  apt: update_cache=yes
- name: install nginx-extras
  apt: name=nginx-extras state=present
- name: install passenger
  apt: name=passenger state=present
- name: uncomment include passenger.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: apt update
  apt: update_cache=yes
- name: copying redmine-nginx.conf
  template: src=default.j2 dest=/etc/nginx/sites-available/default
- name: restart nginx
  systemd: name=nginx state=restarted
#- name: Upgrade all packages to the latest version
#  apt: name="*" state=latest

#- name: Dependencies
#  apt: name=ruby-dev state=present
#- name: dependecies tanya
#  apt: name=libcurl4-gnutls-dev state=present
